version: "3"

services:
  mariadb:
    image: mariadb:10.9.4
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: drupal:php8.1-fpm-alpine
    container_name: drupal
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      # /var/www/html is a symlink to /opt/drupal/web
      - drupal-data:/opt/drupal

  webserver:
    image: nginx:stable
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - drupal-data/-web-root-:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - external

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - drupal-data/-web-root-:/var/www/html

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  db-data: